### PR TITLE
Feature/167

### LINKED ISSUE #167: Searching pictograms should not be case sensitive
**Is your feature request related to a problem? Please describe.**
The issue is that searching pictograms yields different result, depending on whether or not the search query contains capital letters.
This is the same as aau-giraf/weekplanner#622, but the problem lies in the web-api.

**Describe the solution you'd like**
To convert the search query and the pictogram titles, to all lowercase letters when they are compared

**Describe alternatives you've considered**
I considered converting the search query to all lowercase, before sending it to the web-api. But in that case it would be compared to pictogram titles that could contain capital letters, which could yield incorrect results

### PR DESCRIPTION
**Pull request by soenderby**
Fixes #167, also fixes aau-giraf/weekplanner#622 which is the same issue but on the weekplanner.

Changed the algorithm for pictogram search, added some tests, and did some refactoring.

### CODE REVIEW

**Comment by Determinatoro** [comment]
Please use the following checklist, @LJensen0403. Feel free to check it off as you go along.

**Code Design** 

- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems     
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code does not introduce functionality that is unnecessary for solving the problem

**Code Readability** 

- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no \"hack\", or obscure solution   

**Code Maintainability**

- [ ] Has all the added code been properly commented

Only check one of the items below:

- [ ] The functionality does **not** need to be covered by tests
- [ ] The functionality needs to be covered by tests

Only check these if the functionality needs to be covered by tests:

- [ ] All functionality is covered by tests
- [ ] The tests has sensible names
- [ ] By reading the tests you know what they cover
- [ ] The tests cover sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing

**Functionality**

For this part, run the web-api locally as described in https://aau-giraf.github.io/wiki/development/rest_api_development/BuildAndRunLocally/ 
- [ ] The web-api runs without issues
- [ ] The functionality that the code claims to implement, are actually implemented
- [ ] The integration tests runs successfully. Refer to https://github.com/aau-giraf/web-api/tree/master/GirafIntegrationTest for how to run the tests

**Comment by Determinatoro** [comment]
Please use the following checklist, @Riasalit. Feel free to check it off as you go along.

**Code Design** 

- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems     
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code does not introduce functionality that is unnecessary for solving the problem

**Code Readability** 

- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no \"hack\", or obscure solution   

**Code Maintainability**

- [ ] Has all the added code been properly commented

Only check one of the items below:

- [ ] The functionality does **not** need to be covered by tests
- [ ] The functionality needs to be covered by tests

Only check these if the functionality needs to be covered by tests:

- [ ] All functionality is covered by tests
- [ ] The tests has sensible names
- [ ] By reading the tests you know what they cover
- [ ] The tests cover sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing

**Functionality**

For this part, run the web-api locally as described in https://aau-giraf.github.io/wiki/development/rest_api_development/BuildAndRunLocally/ 
- [ ] The web-api runs without issues
- [ ] The functionality that the code claims to implement, are actually implemented
- [ ] The integration tests runs successfully. Refer to https://github.com/aau-giraf/web-api/tree/master/GirafIntegrationTest for how to run the tests

**Review by Riasalit — CHANGES_REQUESTED** [review]
Integration tests fejler

**Comment by soenderby** [comment]
Fixed it, integrations tests passer nu. Det viser sig at jeg ikke kan finde ud af Entity Framwork.

**Review by Riasalit — APPROVED** [review]

**Review by LJensen0403 — APPROVED** [review]

**Pull request merged**
