### PR TITLE
Feature/91

### LINKED ISSUE #91: Remove redundant endpoint
The endpoint `/v1/Department/{departmentId}/user/{userId}` adds a user *that does not have a department* to department with id `departmentId`. However, it is not possible to register a user without specifying a department, and additionally, when you delete a department, any user belonging to that department is also deleted. As such, it is not possible to have a user that does not belong to a department. The aforementioned endpoint should be removed, or a user should be able to exist without a department.

### PR DESCRIPTION
**Pull request by JeppeKLau**
Removed the redundant endpoint, and any tests linked to the endpoint, mentioned in #91
This pull request closes #91

### CODE REVIEW

**Comment by Determinatoro** [comment]
Please use the following checklist, @Oliversrensen. Feel free to check it off as you go along.

**Code Design** 

- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems     
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code does not introduce functionality that is unnecessary for solving the problem

**Code Readability** 

- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no \"hack\", or obscure solution   

**Code Maintainability**

- [ ] Has all the added code been properly commented

Only check one of the items below:

- [ ] The functionality does **not** need to be covered by tests
- [ ] The functionality needs to be covered by tests

Only check these if the functionality needs to be covered by tests:

- [ ] All functionality is covered by tests
- [ ] The tests has sensible names
- [ ] By reading the tests you know what they cover
- [ ] The tests cover sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing

**Functionality**

For this part, run the web-api locally as described in https://aau-giraf.github.io/wiki/development/rest_api_development/BuildAndRunLocally/ 
- [ ] The web-api runs without issues
- [ ] The functionality that the code claims to implement, are actually implemented
- [ ] The integration tests runs successfully. Refer to https://github.com/aau-giraf/web-api/tree/master/GirafIntegrationTest for how to run the tests

**Comment by Determinatoro** [comment]
Please use the following checklist, @smh87. Feel free to check it off as you go along.

**Code Design** 

- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems     
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code does not introduce functionality that is unnecessary for solving the problem

**Code Readability** 

- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no \"hack\", or obscure solution   

**Code Maintainability**

- [ ] Has all the added code been properly commented

Only check one of the items below:

- [ ] The functionality does **not** need to be covered by tests
- [ ] The functionality needs to be covered by tests

Only check these if the functionality needs to be covered by tests:

- [ ] All functionality is covered by tests
- [ ] The tests has sensible names
- [ ] By reading the tests you know what they cover
- [ ] The tests cover sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing

**Functionality**

For this part, run the web-api locally as described in https://aau-giraf.github.io/wiki/development/rest_api_development/BuildAndRunLocally/ 
- [ ] The web-api runs without issues
- [ ] The functionality that the code claims to implement, are actually implemented
- [ ] The integration tests runs successfully. Refer to https://github.com/aau-giraf/web-api/tree/master/GirafIntegrationTest for how to run the tests

**Review by smh87 — CHANGES_REQUESTED** [review]
Have you checked if there are references to the deleted files any where else?

**Comment by JeppeKLau** [comment]
> 
> 
> Have you checked if there are references to the deleted files any where else?

Do you know of a reference I missed?

**Review by smh87 — APPROVED** [review]

**Review by Oliversrensen — APPROVED** [review]

**Pull request merged**
