### PR TITLE
Feature 170: added api support for alternate names to activities

### LINKED ISSUE #170: As a developer I would like support for renaming activities locally
**Is your feature request related to a problem? Please describe.**
This issue is related to aau-giraf/weekplanner#266 and aau-giraf/api-client#76

**Describe the solution you'd like**
Models and endpoint should be extended to support renaming activities for each citizen.

### PR DESCRIPTION
**Pull request by AdrianPlesner**
Closes #170

### CODE REVIEW

**Comment by Determinatoro** [comment]
Please use the following checklist, @Mustafa-ALD. Feel free to check it off as you go along.

**Code Design** 

- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems     
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code does not introduce functionality that is unnecessary for solving the problem

**Code Readability** 

- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no \"hack\", or obscure solution   

**Code Maintainability**

- [ ] Has all the added code been properly commented

Only check one of the items below:

- [ ] The functionality does **not** need to be covered by tests
- [ ] The functionality needs to be covered by tests

Only check these if the functionality needs to be covered by tests:

- [ ] All functionality is covered by tests
- [ ] The tests has sensible names
- [ ] By reading the tests you know what they cover
- [ ] The tests cover sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing

**Functionality**

For this part, run the web-api locally as described in https://aau-giraf.github.io/wiki/development/rest_api_development/BuildAndRunLocally/ 
- [ ] The web-api runs without issues
- [ ] The functionality that the code claims to implement, are actually implemented
- [ ] The integration tests runs successfully. Refer to https://github.com/aau-giraf/web-api/tree/master/GirafIntegrationTest for how to run the tests

**Comment by Determinatoro** [comment]
Please use the following checklist, @smh87. Feel free to check it off as you go along.

**Code Design** 

- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems     
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code does not introduce functionality that is unnecessary for solving the problem

**Code Readability** 

- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no \"hack\", or obscure solution   

**Code Maintainability**

- [ ] Has all the added code been properly commented

Only check one of the items below:

- [ ] The functionality does **not** need to be covered by tests
- [ ] The functionality needs to be covered by tests

Only check these if the functionality needs to be covered by tests:

- [ ] All functionality is covered by tests
- [ ] The tests has sensible names
- [ ] By reading the tests you know what they cover
- [ ] The tests cover sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing

**Functionality**

For this part, run the web-api locally as described in https://aau-giraf.github.io/wiki/development/rest_api_development/BuildAndRunLocally/ 
- [ ] The web-api runs without issues
- [ ] The functionality that the code claims to implement, are actually implemented
- [ ] The integration tests runs successfully. Refer to https://github.com/aau-giraf/web-api/tree/master/GirafIntegrationTest for how to run the tests

**Comment by Mustafa-ALD** [comment]
I unfortunatly can't run the api locally. I thought I did something wrong, but I can run another older version of the api and then I tried again with this new one and it didn't work.
I did go through and double check the steps of [Build and Run the web-api locally](https://aau-giraf.github.io/wiki/development/rest_api_development/BuildAndRunLocally/).
 
When I try to run it i get these errors.
image
image

**Comment by Mustafa-ALD** [comment]
I would just like to add the information of my environment:

OS: Android
Emulator: yes
Phone: Pixel C
APK Version: 30

**Comment by AdrianPlesner** [comment]
@Mustafa-ALD if you are trying to connect to the week planner app, you should use the right version of the api_client library (feature/76) and if you actually want to see it work in the weekplan, use branch feature/266 but keep in mind that the front-end is not yet complete.

**Review by Mustafa-ALD — APPROVED** [review]

**Review by smh87 — CHANGES_REQUESTED** [review]
I cannot run the weekplanner feature/266 where i tried to test the web-API, see attahed file
[week-planer-build-failed.txt](https://github.com/aau-giraf/web-api/files/5589524/week-planer-build-failed.txt)
. So this pull request should not be merged before it is tested with weekplanner.

**Comment by AdrianPlesner** [comment]
> I cannot run the weekplanner feature/266 where i tried to test the web-API, see attached file
> [week-planer-build-failed.txt](https://github.com/aau-giraf/web-api/files/5589524/week-planer-build-failed.txt)
> . So this pull request should not be merged before it is tested with weekplanner.

@smh87 It looks like you are not using the right version of api_client. Be aware that simply running pub-get might not be enough because of caching.

**Review by smh87 — APPROVED** [review]

**Pull request merged**
