### PR TITLE
Fixes 52

### PR DESCRIPTION
**Pull request by Seraph2**
This is a major upgrade from .NET Core 2.2 to 3.1.
It fixes issue #52

For the testers, here are some ressources:
[Download .NET Core 3.1][core31]

You may need to regenerate your test database. This can be done with the following:
Depending if you get an error on `dotnet ef`, you may need to install the [efcore cli tool][efcorecli] using this command:
```bash
dotnet tool install --global dotnet-ef
```
Now you are ready to regenerate the database (Remember to alter the connection string if you want to use a different database)
```bash
dotnet ef database drop #Drops the current database
dotnet ef database update #Recreates the database schema
dotnet run --sample-data #Runs the project creating sample data in the database
```

The tests in `GirafRest.Test` can be run using this command:
```
dotnet test
```

The tests in `GirafIntegrationTest` requires python 3 and can then be run using this command:
```
python3 test.py
```

Please note that some of the integration tests may fail because there are some dependencies on the sample data generated in the web-api. There is an issue for it #93

[core31]: https://dotnet.microsoft.com/download/dotnet-core/3.1
[efcorecli]: https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet

### CODE REVIEW

**Comment by joandrsn** [comment]
Integration tests:
image
`GirafRest.Test`
image

**Comment by joandrsn** [comment]
Sorry, you don't need to approve just yet. There have been an error in #89 which has impacted how this issue can be merged. I have notified @frederikspang about it.

**Comment by MrPekar98** [comment]
@joandrsn Yep, that was a mistake. If you will add more changes, can you convert this PR into draft in the mean time?

**Comment by joandrsn** [comment]
My output from running the tests inside `GirafRest.Test`:
```
Test Run Successful.
Total tests: 363
     Passed: 363
 Total time: 5.5370 Seconds
```

Integration tests:
```
Ran 207 tests in 5.261s
182 passed (0 unexpected), 3 errors, 22 failed (0 expected), 0 skipped
```

Currently there is a problem where many tests fail because the integration tests are dependent on the ID's given by the database. After PR #90 the departments are created in the "wrong" order.
After fixing the department error, this is the output from the integration tests:
```
198 passed (0 unexpected), 3 errors, 6 failed (0 expected), 0 skipped
```

These failing integration tests are because tests are not independant (#93):
- Testing getting specific template
- Testing getting single public pictogram
- Testing getting all pictograms

These tests are because they need some work (Will fail for everyone currently):
- Testing if a superuser can delete the userIcon of another user
- Testing PATCH update to activity for a specific user
- Testing DELETE on user specific activity
- Testing if a superuser can get the raw userIcon of another user
- Testing PATCHING of activity or updating it without authentication token

This test is special since it actually tries to create a `Pictogram` with a `Title` being `NULL`. This is not a fail written by the test, but the endpoint doing something invalid.
- Testing creation of user specific activity

**Comment by MrPekar98** [comment]
Will you create a new issue for independency problem you mentioned?

**Comment by joandrsn** [comment]
@MrPekar98 I don't quite understand. I have already created #93

**Comment by MrPekar98** [comment]
@joandrsn Oh, sorry. I didn't see that.

**Pull request merged**
