### PR TITLE
Fixes 46

### LINKED ISSUE #46: Don´t know what HugeBase64Images.cs is used for
I don't understand what it's there for anymore. As I see it, it has no references, and simply contains 66K characters.

It could possibly be one large image or many small images.

It's located in [HugeBase64Images.cs](https://github.com/aau-giraf/web-api/blob/master/GirafRest/Data/HugeBase64Images.cs) (`GirafRest/Data/HugeBase64Images.cs`).

To quote the code:
```
/*
 * Beware ye who enters.
 *
 * Here be very long lines.
 */
```

### PR DESCRIPTION
**Pull request by mathiasandresen**
closes #46

### CODE REVIEW

**Comment by Lortemanden** [comment]
@jollycola So I guess you decided to delete it since it's not used?

**Comment by elaurs** [comment]
What is the file used for? And is it ensured that the removal of the file does not affect the application?

**Comment by jollycola** [comment]
we deleted the file, since there are no references to it, and all tests are succesful.
If we somehow need the file later, we can always find it in version control.

**Comment by elaurs** [comment]
Sorry. I didn't see we were three people to approve it already, do you have any objections @Lortemanden ?

**Pull request merged**
