### PR TITLE
Feature/167

### LINKED ISSUE #167: Searching pictograms should not be case sensitive
**Is your feature request related to a problem? Please describe.**
The issue is that searching pictograms yields different result, depending on whether or not the search query contains capital letters.
This is the same as aau-giraf/weekplanner#622, but the problem lies in the web-api.

**Describe the solution you'd like**
To convert the search query and the pictogram titles, to all lowercase letters when they are compared

**Describe alternatives you've considered**
I considered converting the search query to all lowercase, before sending it to the web-api. But in that case it would be compared to pictogram titles that could contain capital letters, which could yield incorrect results

### PR DESCRIPTION
**Pull request by dkalaxdk**
closes #167

### CODE REVIEW

**Comment by kbwsoorensen** [comment]
Er der en grund til at Master er target? Ellers burde det vel være Develop.

**Comment by dkalaxdk** [comment]
Nej, det var en brainfart, skal jeg lukke den og lave det til develop?

**Comment by kbwsoorensen** [comment]
> 
> 
> Nej, det var en brainfart, skal jeg lukke den og lave det til develop?

Skulle til at sige nej, men kan se jeg ikke behøver at gøre det. Der er dog conflicts der skal resolves.

**Comment by Determinatoro** [comment]
Please use the following checklist, @kbwsoorensen. Feel free to check it off as you go along.

**Code Design** 

- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems     
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code does not introduce functionality that is unnecessary for solving the problem

**Code Readability** 

- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no \"hack\", or obscure solution   

**Code Maintainability**

- [ ] Has all the added code been properly commented

Only check one of the items below:

- [ ] The functionality does **not** need to be covered by tests
- [ ] The functionality needs to be covered by tests

Only check these if the functionality needs to be covered by tests:

- [ ] All functionality is covered by tests
- [ ] The tests has sensible names
- [ ] By reading the tests you know what they cover
- [ ] The tests cover sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing

**Functionality**

For this part, run the web-api locally as described in https://aau-giraf.github.io/wiki/development/rest_api_development/BuildAndRunLocally/ 
- [ ] The web-api runs without issues
- [ ] The functionality that the code claims to implement, are actually implemented
- [ ] The integration tests runs successfully. Refer to https://github.com/aau-giraf/web-api/tree/master/GirafIntegrationTest for how to run the tests

**Comment by Determinatoro** [comment]
Please use the following checklist, @Determinatoro. Feel free to check it off as you go along.

**Code Design** 

- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems     
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code does not introduce functionality that is unnecessary for solving the problem

**Code Readability** 

- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no \"hack\", or obscure solution   

**Code Maintainability**

- [ ] Has all the added code been properly commented

Only check one of the items below:

- [ ] The functionality does **not** need to be covered by tests
- [ ] The functionality needs to be covered by tests

Only check these if the functionality needs to be covered by tests:

- [ ] All functionality is covered by tests
- [ ] The tests has sensible names
- [ ] By reading the tests you know what they cover
- [ ] The tests cover sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing

**Functionality**

For this part, run the web-api locally as described in https://aau-giraf.github.io/wiki/development/rest_api_development/BuildAndRunLocally/ 
- [ ] The web-api runs without issues
- [ ] The functionality that the code claims to implement, are actually implemented
- [ ] The integration tests runs successfully. Refer to https://github.com/aau-giraf/web-api/tree/master/GirafIntegrationTest for how to run the tests

**Comment by Determinatoro** [comment]
Please use the following checklist, @Huften. Feel free to check it off as you go along.

**Code Design** 

- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems     
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code does not introduce functionality that is unnecessary for solving the problem

**Code Readability** 

- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no \"hack\", or obscure solution   

**Code Maintainability**

- [ ] Has all the added code been properly commented

Only check one of the items below:

- [ ] The functionality does **not** need to be covered by tests
- [ ] The functionality needs to be covered by tests

Only check these if the functionality needs to be covered by tests:

- [ ] All functionality is covered by tests
- [ ] The tests has sensible names
- [ ] By reading the tests you know what they cover
- [ ] The tests cover sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing

**Functionality**

For this part, run the web-api locally as described in https://aau-giraf.github.io/wiki/development/rest_api_development/BuildAndRunLocally/ 
- [ ] The web-api runs without issues
- [ ] The functionality that the code claims to implement, are actually implemented
- [ ] The integration tests runs successfully. Refer to https://github.com/aau-giraf/web-api/tree/master/GirafIntegrationTest for how to run the tests

**Comment by Determinatoro** [comment]
Please use the following checklist, @ProgDaniel. Feel free to check it off as you go along.

**Code Design** 

- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems     
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code does not introduce functionality that is unnecessary for solving the problem

**Code Readability** 

- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no \"hack\", or obscure solution   

**Code Maintainability**

- [ ] Has all the added code been properly commented

Only check one of the items below:

- [ ] The functionality does **not** need to be covered by tests
- [ ] The functionality needs to be covered by tests

Only check these if the functionality needs to be covered by tests:

- [ ] All functionality is covered by tests
- [ ] The tests has sensible names
- [ ] By reading the tests you know what they cover
- [ ] The tests cover sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing

**Functionality**

For this part, run the web-api locally as described in https://aau-giraf.github.io/wiki/development/rest_api_development/BuildAndRunLocally/ 
- [ ] The web-api runs without issues
- [ ] The functionality that the code claims to implement, are actually implemented
- [ ] The integration tests runs successfully. Refer to https://github.com/aau-giraf/web-api/tree/master/GirafIntegrationTest for how to run the tests

**Review by ProgDaniel — CHANGES_REQUESTED** [review]
It is very hard to see changes in the PictogramControllerTest.cs and UnitTestExtensions.cs when all lines have been changed. I assume this is because of a IDE that have changed all line endings in the files. Can this be reverted (while keeping the new changes)

**Comment by ProgDaniel** [comment]
Also, has this not been solved in #169, or is this a new issue?

**Comment by ProgDaniel** [comment]
4 integration tests seem to fail in the web-api integration test
image

**Comment by dkalaxdk** [comment]
The issue has been reopened, as the first solution had some more errors in it, and it is therefore reopened.

The integration tests are also run online in CI, and does not return errors on my machine or on github?

**Comment by Rosmarium** [comment]
Hej. GitHub Actions smider nogle warnings ud med declared but unused variables.

**Comment by dkalaxdk** [comment]
Hvor henne er det de smider disse?
Det er ikke ummidelbart noget jeg har lagt mærke til

**Comment by Rosmarium** [comment]
image
Får dem herinde under files changed.

**Comment by dkalaxdk** [comment]
Det er elementer fra noget vi ikke har kigget på ifht løsningen af denne opgave.
Dog er det en fejlhåndtering i tilfælde af at serveren ikke har skrive rettigheder til en fil

**Comment by Rosmarium** [comment]
Jeg tænkte også, det ikke havde noget med jeres at gøre, men ville bare høre om det var fordi I havde slettet noget. Så det er bare super :)

**Review by Rosmarium — APPROVED** [review]

**Comment by dkalaxdk** [comment]
@Rosmarium Hvis du har overtaget for Johan, kan du så ikke fjerne ham som reviewer :)

**Comment by Rosmarium** [comment]
Troede jeg, jeg havde gjort, men kan se, det ikke lgie var gået igennem :)

**Comment by ProgDaniel** [comment]
I used the tests described through the [GIRAF Integration test](https://github.com/aau-giraf/web-api/tree/master/GirafIntegrationTest). Running those tests returns the following:

199 passed (0 unexpected), 14 errors, 4 failed (0 expected), 4 skipped

If you can try to run the tests and get no errors, then I assume it may be on my end and I can approve it

**Comment by dkalaxdk** [comment]
They all work in on my end and on CI :)

**Review by ProgDaniel — APPROVED** [review]

**Review by Rosmarium — APPROVED** [review]

**Pull request merged**
